import json
import ollama


# =========================================================
# SAFE TEXT HELPER
# =========================================================

def clean_text(value, fallback=""):
    if value is None:
        return fallback

    if isinstance(value, str):
        value = value.strip()

        if value:
            return value

    return fallback


# =========================================================
# NORMALIZE SCENE
# =========================================================

def normalize_scene(scene, index):
    if not isinstance(scene, dict):
        scene = {}

    scene_number = (
        scene.get("scene_number")
        or scene.get("sceneNumber")
        or scene.get("number")
        or index + 1
    )

    try:
        scene_number = int(scene_number)
    except Exception:
        scene_number = index + 1

    duration = (
        scene.get("duration_seconds")
        or scene.get("duration")
        or scene.get("durationSeconds")
        or 5
    )

    try:
        duration = int(duration)
    except Exception:
        duration = 5

    description = clean_text(
        scene.get("description")
        or scene.get("scene_description")
        or scene.get("sceneDescription")
        or scene.get("action")
        or scene.get("visual_description"),
        "Scene description generated by AI."
    )

    visual_prompt = clean_text(
        scene.get("visual_prompt")
        or scene.get("visualPrompt")
        or scene.get("image_prompt")
        or scene.get("imagePrompt")
        or scene.get("visual"),
        "Cinematic advertising shot, premium lighting, high quality commercial photography."
    )

    voiceover = clean_text(
        scene.get("voiceover")
        or scene.get("voice_over")
        or scene.get("voiceOver")
        or scene.get("narration")
        or scene.get("audio"),
        "Experience something better, starting today."
    )

    caption = clean_text(
        scene.get("caption")
        or scene.get("on_screen_text")
        or scene.get("onScreenText")
        or scene.get("text")
        or scene.get("subtitle"),
        "Experience the difference."
    )

    return {
        "scene_number": scene_number,
        "duration_seconds": duration,
        "description": description,
        "visual_prompt": visual_prompt,
        "voiceover": voiceover,
        "caption": caption,
    }


# =========================================================
# CREATIVE DIRECTOR
# =========================================================

def create_creative_plan(brief: str):

    prompt = f"""
You are an expert AI Creative Director working for HexCoded.

Your job is to transform the creative brief into a professional
advertising production plan.

CREATIVE BRIEF:
{brief}

Create a complete advertising campaign.

The campaign MUST contain exactly THREE scenes.

For EVERY scene you MUST provide:

- scene_number
- duration_seconds
- description
- visual_prompt
- voiceover
- caption

IMPORTANT:

Do not leave any field empty.

Do not omit any field.

Do not use null.

Do not return explanations.

Return ONLY valid JSON.

Use EXACTLY this structure:

{{
    "campaign_name": "string",
    "target_audience": "string",
    "creative_concept": "string",
    "tone": "string",
    "platform": "string",
    "duration_seconds": 20,
    "aspect_ratio": "9:16",

    "scenes": [
        {{
            "scene_number": 1,
            "duration_seconds": 6,
            "description": "Detailed description of what happens in scene 1.",
            "visual_prompt": "Detailed cinematic visual generation prompt for scene 1.",
            "voiceover": "Voiceover spoken during scene 1.",
            "caption": "Short on-screen caption for scene 1."
        }},

        {{
            "scene_number": 2,
            "duration_seconds": 7,
            "description": "Detailed description of what happens in scene 2.",
            "visual_prompt": "Detailed cinematic visual generation prompt for scene 2.",
            "voiceover": "Voiceover spoken during scene 2.",
            "caption": "Short on-screen caption for scene 2."
        }},

        {{
            "scene_number": 3,
            "duration_seconds": 7,
            "description": "Detailed description of what happens in scene 3.",
            "visual_prompt": "Detailed cinematic visual generation prompt for scene 3.",
            "voiceover": "Voiceover spoken during scene 3.",
            "caption": "Short on-screen caption for scene 3."
        }}
    ],

    "final_voiceover": "Final campaign voiceover.",
    "final_caption": "Final campaign call to action."
}}

Remember:

EVERY scene MUST contain real text for:

description
visual_prompt
voiceover
caption
"""

    print("\n========================================")
    print("CREATIVE DIRECTOR STARTED")
    print("========================================")

    try:

        response = ollama.chat(
            model="llama3.2",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            format="json"
        )

        raw_response = (
            response
            .get("message", {})
            .get("content", "")
            .strip()
        )

        print("\n========================================")
        print("RAW OLLAMA RESPONSE")
        print("========================================")
        print(raw_response)
        print("========================================\n")

        if not raw_response:
            raise ValueError(
                "Ollama returned an empty response."
            )

        # -------------------------------------------------
        # REMOVE MARKDOWN FENCES IF PRESENT
        # -------------------------------------------------

        if raw_response.startswith("```"):
            raw_response = raw_response.replace(
                "```json",
                "",
                1
            )

            raw_response = raw_response.replace(
                "```",
                "",
                1
            ).strip()

        # -------------------------------------------------
        # EXTRACT JSON OBJECT
        # -------------------------------------------------

        start = raw_response.find("{")
        end = raw_response.rfind("}")

        if start == -1 or end == -1:
            raise ValueError(
                "Ollama response does not contain valid JSON."
            )

        json_text = raw_response[
            start:end + 1
        ]

        # -------------------------------------------------
        # PARSE JSON
        # -------------------------------------------------

        try:
            result = json.loads(
                json_text
            )

        except json.JSONDecodeError as e:
            print(
                "JSON PARSE ERROR:",
                e
            )

            print(
                "JSON RECEIVED:",
                json_text
            )

            raise ValueError(
                "AI returned invalid JSON."
            )

        # -------------------------------------------------
        # VALIDATE OBJECT
        # -------------------------------------------------

        if not isinstance(result, dict):
            raise ValueError(
                "AI response is not a JSON object."
            )

        # -------------------------------------------------
        # GET RAW SCENES
        # -------------------------------------------------

        raw_scenes = result.get(
            "scenes",
            []
        )

        if not isinstance(
            raw_scenes,
            list
        ):
            raw_scenes = []

        # -------------------------------------------------
        # NORMALIZE SCENES
        # -------------------------------------------------

        scenes = []

        for index, scene in enumerate(
            raw_scenes[:3]
        ):

            normalized = normalize_scene(
                scene,
                index
            )

            scenes.append(
                normalized
            )

        # -------------------------------------------------
        # GUARANTEE THREE SCENES
        # -------------------------------------------------

        while len(scenes) < 3:

            scene_number = (
                len(scenes) + 1
            )

            scenes.append(
                normalize_scene(
                    {
                        "scene_number":
                            scene_number,
                        "duration_seconds":
                            5,
                    },
                    scene_number - 1
                )
            )

        # -------------------------------------------------
        # FORCE EXACTLY THREE
        # -------------------------------------------------

        scenes = scenes[:3]

        # -------------------------------------------------
        # BUILD FINAL WORKFLOW
        # -------------------------------------------------

        workflow = {

            "campaign_name":
                clean_text(
                    result.get(
                        "campaign_name"
                    ),
                    "AI Advertising Campaign"
                ),

            "target_audience":
                clean_text(
                    result.get(
                        "target_audience"
                    ),
                    "Young professionals"
                ),

            "creative_concept":
                clean_text(
                    result.get(
                        "creative_concept"
                    ),
                    "Modern premium advertising concept"
                ),

            "tone":
                clean_text(
                    result.get(
                        "tone"
                    ),
                    "Modern and premium"
                ),

            "platform":
                clean_text(
                    result.get(
                        "platform"
                    ),
                    "Instagram"
                ),

            "duration_seconds":
                sum(
                    scene[
                        "duration_seconds"
                    ]
                    for scene in scenes
                ),

            "aspect_ratio":
                clean_text(
                    result.get(
                        "aspect_ratio"
                    ),
                    "9:16"
                ),

            "scenes":
                scenes,

            "final_voiceover":
                clean_text(
                    result.get(
                        "final_voiceover"
                    ),
                    "Experience the difference today."
                ),

            "final_caption":
                clean_text(
                    result.get(
                        "final_caption"
                    ),
                    "Experience the difference."
                ),
        }

        # -------------------------------------------------
        # PRINT FINAL WORKFLOW
        # -------------------------------------------------

        print("\n========================================")
        print("FINAL WORKFLOW SENT TO FRONTEND")
        print("========================================")

        print(
            json.dumps(
                workflow,
                indent=4,
                ensure_ascii=False
            )
        )

        print("========================================\n")

        return workflow

    except Exception as e:

        print("\n========================================")
        print("CREATIVE DIRECTOR ERROR")
        print("========================================")
        print(str(e))
        print("========================================\n")

        raise